# Generated by Django 5.1.3 on 2024-11-14 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FirstApp', '0005_client_last_interest_update'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='daily_interest_amount',
            new_name='total_interest',
        ),
        migrations.RemoveField(
            model_name='client',
            name='last_interest_update',
        ),
        migrations.RemoveField(
            model_name='client',
            name='remove_amount',
        ),
        migrations.AddField(
            model_name='client',
            name='delete_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='add_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
