# Generated by Django 5.1.3 on 2024-11-15 02:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FirstApp', '0006_rename_daily_interest_amount_client_total_interest_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
