# Generated by Django 5.1.3 on 2024-11-15 03:18

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FirstApp', '0007_alter_client_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=10),
        ),
    ]
