# Generated by Django 5.1.3 on 2024-11-16 16:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FirstApp', '0008_client_total_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
