# Generated by Django 5.1.3 on 2024-11-16 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FirstApp', '0009_alter_client_start_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='add_amount',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='delete_amount',
            new_name='amount_add',
        ),
        migrations.RemoveField(
            model_name='client',
            name='given_amount',
        ),
        migrations.RemoveField(
            model_name='client',
            name='total_interest',
        ),
        migrations.AddField(
            model_name='client',
            name='amount_delete',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='interest',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='interest_add',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='interest_delete',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
